# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductID',
            fields=[
                ('ARTICLE', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CATEGORY', models.CharField(max_length=500)),
                ('SEASON', models.CharField(max_length=500)),
                ('MATERIAL1', models.CharField(max_length=500)),
                ('MATERIAL2', models.CharField(max_length=500)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('BRAND', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLOR', models.CharField(max_length=500)),
                ('GENDER', models.CharField(max_length=500)),
                ('WHOLEPRICE', models.CharField(max_length=500)),
                ('RETAILPRICE', models.CharField(max_length=500)),
                ('AGE', models.CharField(max_length=500)),
                ('SIZE', models.CharField(max_length=500)),
                ('ARTICLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.ProductID')),
            ],
        ),
    ]
