# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ARTICLE', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('BRAND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Brand')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Category')),
                ('MATERIALS', models.ManyToManyField(to='API_app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WHOLEPRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RETAILPRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Age')),
                ('ARTICLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Product')),
                ('COLOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Color')),
                ('GENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('NAME', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='productvar',
            name='SIZE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_app.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='SEASON',
            field=models.ManyToManyField(to='API_app.Season'),
        ),
    ]
