# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0004_auto_20170603_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MATERIALS',
            field=models.ManyToManyField(blank=True, to='API_app.Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SEASON',
            field=models.ManyToManyField(blank=True, to='API_app.Season'),
        ),
    ]
